# Generated by Django 5.1.1 on 2024-12-11 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Type_Utilisateur",
            fields=[
                (
                    "id_type_utilisateur",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("type_utilisateur", models.CharField(max_length=50)),
                ("role_utilisateur", models.CharField(max_length=100)),
                ("is_admin", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                ("id_utilisateur", models.AutoField(primary_key=True, serialize=False)),
                ("nom_utilisateur", models.CharField(max_length=100)),
                ("bio_utilisateur", models.CharField(max_length=200)),
                (
                    "type_utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Utilisateur.type_utilisateur",
                    ),
                ),
            ],
        ),
    ]
