# Generated by Django 5.1.1 on 2024-12-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Utilisateur", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="photo_utilisateur",
            field=models.ImageField(default=1, upload_to="utilisateurs"),
            preserve_default=False,
        ),
    ]
