# Generated by Django 5.1.1 on 2024-12-11 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evenement",
            fields=[
                ("id_evenement", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("nombre_participant", models.PositiveIntegerField()),
                ("date_debut", models.DateTimeField()),
                ("date_fin", models.DateTimeField()),
                ("heure", models.TimeField()),
                ("lieu", models.CharField(max_length=255)),
                ("image_evenement", models.ImageField(upload_to="evenements/")),
            ],
        ),
        migrations.CreateModel(
            name="Type_Evenement",
            fields=[
                (
                    "id_type_evenement",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nom_type_evenement", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                ("id_inscription", models.AutoField(primary_key=True, serialize=False)),
                ("est_inscrit", models.BooleanField(default=True)),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Evenement.evenement",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
