# Generated by Django 5.1.1 on 2024-12-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Evenement", "0002_evenement_type_evenement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="date_debut",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="date_fin",
            field=models.DateField(),
        ),
    ]
